### ISSUE TITLE
bug about edit 

### ISSUE THREAD

**Issue by lovepeacemz** [seart-group/java-tree-sitter#102]
hello, i find when i use eidt, the text to replace text contains '*' or '-'  or '.' in annotion , such as "@PostMapping("/code-interpreter")",  parse a new tree from old has problems. the tree cantines error leaf nodes.

**Comment by dabico** [comment]
Hi @lovepeacemz 

It would mean a lot to us if you could give a minimal reproducible example. You should include:
- The source code you have written to do parsing and edits
- An example source file that you are trying to parse/edit
- AST print-outs of the `Tree` before and after the edit

Also, could you include information about which library version you are using?

**Comment by lovepeacemz** [comment]
ok,  may be i can solve
