### ISSUE TITLE
Cannot find import ch.usi.si.seart.treesitter.version.TreeSitter;

### ISSUE THREAD

**Issue by hackhaye** [seart-group/java-tree-sitter#135]
we can't find import ch.usi.si.seart.treesitter.version.TreeSitter; it seems no version.TreeSitter in release version
![image](https://github.com/seart-group/java-tree-sitter/assets/48273203/af4988d6-52c0-417e-8ea1-0a49f4b52b2d)

**Comment by dabico** [comment]
Hi @hackhaye 

The `TreeSitter` and `Version` classes should appear in your `target/generated-sources` directory after you run:

```bash
mvn clean package
```

Make sure IntelliJ is set up to also pull sources from that directory.

![Screenshot 2024-02-22 at 11 15 52](https://github.com/seart-group/java-tree-sitter/assets/34584913/97244bb1-24d2-445c-9d53-622522f21444)
