### ISSUE TITLE
failed to build dependency on mac m1

### ISSUE THREAD

**Issue by gsalmh** [seart-group/java-tree-sitter#2]
There were erroros when i executed "mvn clean package" on my mac.
<img width="1218" alt="infoflow 2023-06-20 16-19-56" src="https://github.com/seart-group/java-tree-sitter/assets/33899928/3e64ed8d-89ae-4e30-8d37-fb9433e9edac">

Enviroment:

- Maven 3.9.2
- JDK 11.0.16.1
- Python 3.9.12
- mac infomation: arm64/Darwin Kernel Version 20.5.0

Is there any idea to solve this problem?

**Comment by dabico** [comment]
Hi @gsalmh 

Apologies for not replying sooner. I received no notification of the issue, so it slipped my notice. Judging by the output, I think this is an issue resulting from the dynamic library being built for the incorrect architecture. I only tested this on older Macs, so I was not aware that M1 had these problems.

While I don't have my computer with me (in a plane awaiting takeoff), I can make an educated guess on what you could try. Edit the [arguments](https://github.com/seart-group/java-tree-sitter/blob/master/pom.xml#L330-L334) section of the `build-shared-object-library-macos` execution in `pom.xml` to include:

```xml
<arguments>
  <!-- existing args -->
  <argument>-a</argument>
  <argument>arch64</argument>
</arguments>
```

Let me know if it works after that.
